language: rust
cache: cargo
rust:
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: beta
  fast_finish: true
script:
  - cargo build --workspace --verbose
  - cargo test --workspace --no-fail-fast